/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroSala.java
 *
 * Created on 16/06/2011, 09:45:41
 */
package br.com.cinema.telas;

import br.com.cinema.historico.HistoricoDeSala;
import br.com.cinema.padroes.CinemaSingleton;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class CadastraSala extends javax.swing.JFrame {

    /** Creates new form CadastroSala */
    public CadastraSala() {
        initComponents();
        lblCamposObrigatorios.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        txtQuantidadeDeLugares = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCamposObrigatorios = new javax.swing.JLabel();
        txtQuantidadeDeSalas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblCamposObrigatorios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtQuantidadeDeLugares.setName("txtNumeroDeSalar"); // NOI18N

        jLabel1.setText("Número de salas");

        txtCamposObrigatorios.setText("Quantidade de lugares");

        txtQuantidadeDeSalas.setName("txtNumeroDeSalar"); // NOI18N

        jButton1.setText("Cadastrar");
        jButton1.setName("btnCadastrar"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblCamposObrigatorios.setForeground(new java.awt.Color(204, 0, 51));
        lblCamposObrigatorios.setText("Todos os campos são obrigatórios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(lblCamposObrigatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtQuantidadeDeSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtQuantidadeDeLugares, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCamposObrigatorios))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantidadeDeSalas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCamposObrigatorios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantidadeDeLugares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCamposObrigatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(cadastroValido()) {
            int quantidadeDeLugares = Integer.parseInt(txtQuantidadeDeLugares.getText());
            int quantidadeDeSalas = Integer.parseInt(txtQuantidadeDeSalas.getText());
            
            CinemaSingleton.getInstancia().getCinema().setQuantidadeDeLugares(quantidadeDeLugares);     
            CinemaSingleton.getInstancia().getCinema().setQuantidadeDeSalas(quantidadeDeSalas);
            CinemaSingleton.getInstancia().getCinema().criaSalas();
            
            HistoricoDeSala historicoDeSala = new HistoricoDeSala(quantidadeDeSalas, quantidadeDeLugares);
            try {
                historicoDeSala.gravarHistorico();
            } catch (IOException ex) {
                Logger.getLogger(CadastraSala.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println(CinemaSingleton.getInstancia().getCinema().getSalas());
            this.dispose();
        }
    }                                        

    private boolean cadastroValido() {
        if(txtQuantidadeDeLugares.getText().isEmpty() || txtQuantidadeDeSalas.getText().isEmpty()) {
            lblCamposObrigatorios.setVisible(true);
            return false;
        }
        lblCamposObrigatorios.setVisible(false);
        return true;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.dispose();
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CadastraSala().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCamposObrigatorios;
    private javax.swing.JLabel txtCamposObrigatorios;
    private javax.swing.JTextField txtQuantidadeDeLugares;
    private javax.swing.JTextField txtQuantidadeDeSalas;
    // End of variables declaration                   
}
