/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RelatorioFilmesSemSessao.java
 *
 * Created on 20/06/2011, 09:48:01
 */
package br.com.cinema.telas;

import br.com.cinema.padroes.CinemaSingleton;
import java.util.Map;
import br.com.cinema.demo.Filme;
import br.com.cinema.demo.Sala;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

public class FilmesSemSessao extends javax.swing.JFrame {

    private DefaultTableModel model = new DefaultTableModel();
    
    /** Creates new form RelatorioFilmesSemSessao */
    public FilmesSemSessao() {
        initComponents();        
        model.addColumn("Código");
        model.addColumn("Nome");
        model.addColumn("Genero");
        model.addColumn("Duração");
        model.addColumn("Censura");
        jTable1.setModel(model);        
        preencheFilmesSemSessao();      
    } 
    
    private void preencheFilmesSemSessao() {
        Map<Filme, Map<Sala, List>> sessoesCriadas = CinemaSingleton.getInstancia().getCinema().getSessao().getSessoes();
        
        Set<Filme> filmesEmSessao = sessoesCriadas.keySet();        
        List<Filme> filmesCadastrados = CinemaSingleton.getInstancia().getCinema().getFilmes(); 
        List<Filme> filmesSemSessao = new ArrayList<Filme>();
        
        boolean achou = false;
        for (Filme filmeCadastrado : filmesCadastrados) {            
            achou = false;
            for (Filme filme : filmesEmSessao) {
                if(filmeCadastrado.getCodigo() == filme.getCodigo()) {
                    achou = true;                    
                    System.out.println("achou");
                }                
            }    
            if(!achou) {
                System.out.println("nao achou");
                filmesSemSessao.add(filmeCadastrado);
                achou = false;
            }
        }        
        
        for (Filme filme : filmesSemSessao) {
            model.addRow(new Object[]{filme.getCodigo(), filme.getNome(), filme.getGenero(), filme.getDuracaoEmMinutos(), filme.getCensura()});
        }
        jTable1.setModel(model);         
        System.out.println(filmesSemSessao);
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(416, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(47, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        this.dispose();
}                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FilmesSemSessao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}
